version: "3.7"
services:
  # Setup database service.
  # user environment declaration to set up dbname and password
  # Set the port for host connection to 5344
  database:
    restart: always
    image: postgres:10.10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tktktktktkt
      - POSTGRES_DB=tourkenya_db
    volumes:
      - ./tourkenya_db:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    expose:
      - '5434'
  # Set up the api service
  # Fill in the path of docker file  to be used
  # Allow the api to be connected with port 8000
  # on the host. Sync all files to the tourkenya-api
  # folder in the container.
  # Load env variables to allow the api connect to the db 
  # and set debug options for the app, this case True for
  # development. Pass in the development env secret key.
  api:
    restart: always
    build:
      context: ./
      dockerfile: docker-dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/tourkenya-api
    environment:
      DATABASE_NAME: tourkenya_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: tktktktktkt
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      APP_DEBUG_MODE: $APP_DEBUG_MODE
      SECRET_KEY: $DEVELOPMENT_SECRET_KEY
    depends_on:
      - database
    entrypoint: ["/bin/bash", "/tourkenya-api/docker-dev/start_api.sh"]
    stdin_open: true
    tty: true
